name: Demo Job
run-name: Run Demo Script

on: [push]
jobs:
  demo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Demo Script
        run: echo "This is a demo job running on push event."
        

