name: Demo Job
run-name: Run Demo Script

on: [push]
jobs:
  demo_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Run Demo Script
        run: echo "This is a demo job running on push event."

      - name: dotnet-format
  # You may pin to the exact commit or the version.
  # uses: xt0rted/dotnet-format@0cf110fed823231b56a2e6fdf8e5d62dc34c538b
        uses: xt0rted/dotnet-format@v1.2.0
        with:
    # GITHUB_TOKEN token or a repo scoped PAT
          repo-token: ${{ github.token }}
    # Version of dotnet-format to use
          version: 3 # default is 3
    # Primary action dotnet-format should perform (check for errors or apply fixes)
          action: check # default is check
    # Only changed files in the current pull request should be formatted
          only-changed-files: optional # optional
    # The job should fail if there's a formatting error
          fail-fast: true # optional, default is true
          
